# Generated by Django 4.0.5 on 2022-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=64)),
                ('campaign_type', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('budget', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('biding_strategy', models.CharField(max_length=64)),
                ('spending', models.CharField(max_length=64)),
                ('targeting', models.CharField(max_length=64)),
            ],
        ),
    ]
